accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("", views.main, name="main"),
    path("signup/", views.signup, name="signup"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("index/", views.index, name="index"),
    path("<int:pk>", views.profile, name="profile"),
    path("update/", views.update, name="update"),
    path("password/", views.change_password, name="change_password"),
    path("delete/", views.delete, name="delete"),
    path("<int:pk>/follow/", views.follow, name="follow"),
    path("login/kakao/", views.kakao_request, name="kakao"),
    path("login/kakao/callback/", views.kakao_callback),
    path("login/naver/", views.naver_request, name="naver"),
    path("login/naver/callback/", views.naver_callback),
]

adultonly/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("accounts/", include("allauth.urls")),
    path("articles/", include("articles.urls")),
    path("communities/", include("communities.urls")),
    path("ratings/", include("star_ratings.urls", namespace="ratings")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

communities/urls.py
from django.urls import path
from . import views

app_name = "communities"

urlpatterns = [
    path("board/", views.board, name="board"),
    path("<int:pk>/", views.detail, name="detail"),
    path("create/", views.create, name="create"),
    path("<int:pk>/update/", views.update, name="update"),
    path("<int:pk>/delete/", views.delete, name="delete"),
    path("comments/<int:pk>/", views.create_comment, name="create_comment"),
    path(
        "<int:pk>/comments/<int:comment_pk>/delete/",
        views.delete_comment,
        name="delete_comment",
    ),
]

communities/models.py
from django.db import models
from django.conf import settings


# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=80)
    content = models.TextField()
    image = models.ImageField(upload_to="communities/", blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)


class Comment(models.Model):
    post = models.ForeignKey("Post", on_delete=models.CASCADE)
    content = models.CharField(max_length=200)
    image = models.ImageField(upload_to="communities/comment/", blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

communities/forms.py
from .models import Post, Comment
from django import forms


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = [
            "title",
            "content",
            "image",
        ]
        labels = {
            "title": "제목",
            "content": "내용",
            "image": "사진 첨부",
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = [
            "content",
            "image",
        ]
        labels = {
            "content": "댓글",
            "image": "사진 첨부",
        }

communities/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_safe
from .models import Post, Comment
from .forms import PostForm, CommentForm
from django.core.paginator import Paginator
from django.contrib import messages
from django.contrib.auth.decorators import login_required

# Create your views here.
@require_safe
def board(request):
    print(request.GET.get("user"))
    page = request.GET.get("page", "1")
    posts = Post.objects.order_by("-pk")
    paginator = Paginator(posts, 10)
    page_obj = paginator.get_page(page)
    context = {
        "posts": page_obj,
    }
    return render(request, "communities/board.html", context)


def detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    comment_form = CommentForm()
    context = {
        "post": post,
        "comments": post.comment_set.all(),
        "comment_form": comment_form,
        "total_comments": post.comment_set.count(),
    }
    return render(request, "communities/detail.html", context)


@login_required
def create(request):
    if request.method == "POST":
        post_form = PostForm(request.POST, request.FILES)
        if post_form.is_valid():
            post = post_form.save(commit=False)
            post.user = request.user
            post.save()
            messages.success(request, "작성한 글이 등록되었습니다.")
            return redirect("communities:board")
    else:
        post_form = PostForm()
    context = {
        "post_form": post_form,
    }
    return render(request, "communities/create.html", context)


@login_required
def update(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.user == post.user:
        if request.method == "POST":
            post_form = PostForm(request.POST, request.FILES, instance=post)
            if post_form.is_valid():
                post_form.save()
                messages.success(request, "글이 수정되었습니다.")
                return redirect("communities:detail", post.pk)
        else:
            post_form = PostForm(instance=post)
        context = {
            "post_form": post_form,
            "post_pk": post.pk,
        }
        return render(request, "communities/update.html", context)
    else:
        messages.warning(request, "접근 권한이 없습니다.")
        return redirect("communities:detail", post.pk)


@login_required
def delete(request, pk):
    post = Post.objects.get(pk=pk)
    if request.user == post.user:
        if request.method == "POST":
            post.delete()
            messages.success(request, "글이 삭제되었습니다.")
            return redirect("communities:board")
        context = {
            "post": post,
        }
        return redirect("communities:detail", context)
    else:
        messages.warning(request, "접근 권한이 없습니다.")
        return redirect("communities:detail", post.pk)


@login_required
def create_comment(request, pk):
    post = get_object_or_404(Post, pk=pk)
    comment_form = CommentForm(request.POST, request.FILES)
    if comment_form.is_valid():
        comment = comment_form.save(commit=False)
        comment.post = post
        comment.user = request.user
        comment.save()
        context = {
            "content": comment.content,
            "username": comment.user.username,
        }
    return redirect("communities:detail", post.pk)


# @login_required
# def update_comment(request, pk):


@login_required
def delete_comment(request, pk, comment_pk):
    comment = get_object_or_404(Comment, pk=comment_pk)
    if request.user == comment.user:
        comment.delete()
        messages.success(request, "댓글이 삭제되었습니다.")
        return redirect("communities:detail", pk)
    else:
        messages.warning(request, "작성자만 삭제할 수 있습니다.")
        return redirect("communities:detail", pk)

communities/templates/communities/board.html
{% extends 'base.html' %}

{% load static %}
{% load django_bootstrap5 %}

{% block content %}
<section class="mainbg">
  <div class="container-lg">
    <h1 class="text-center">자유게시판</h1>
    <a href="{% url 'communities:create' %}" class="btn btn-all">글쓰기</a>
    <!-- 게시글 목록 -->
    <div class="boxbg p-3" style="min-height: 400px;">
      <table class="table table-hover my-3" style="border-radius: 0.7rem; box-shadow: 2px 2px 2px 2px black; margin-bottom: 3rem;">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">제목</th>
            <th scope="col">작성자</th>
            <th scope="col">등록일</th>
          </tr>
        </thead>
        <tbody>
          {% for post in posts %}
            <tr class="table-active">
              <th scope="row">{{ forloop.revcounter }}</th>
              <td style="background-color: linear-gradient(rgba(125,125,125,0.9), rgba(125,125,125,0.9));">
                <div class="d-flex justify-content-between">
                  <a href="{% url 'communities:detail' post.pk %}">{{ post.title }}</a>
                  <span>
                    <i class="fa-solid fa-comment"></i>{{ post.comment_set.all|length }}</span>
                </div>
              </td>
              <td style="background-color: linear-gradient(rgba(125,125,125,0.9), rgba(125,125,125,0.9));">
                <div class="thumb_profile">
                  {% if user.profile_pic %}
                  <a href="{% url 'accounts:profile' post.user.pk %}"><img src="{{ post.user.profile_pic.url }}" class="img_profile" alt="프로필사진"></a>
                  {% else %}
                  <img src="{% static 'img/anonymous.png' %}" class="img_profile" alt="프로필사진">
                  {% endif %}
                </div>
                {{ post.user }}
              </td>
              <td style="background-color: linear-gradient(rgba(125,125,125,0.9), rgba(125,125,125,0.9));">{{ post.created_at }}</td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
    <!-- 페이징처리 시작 -->
    <ul class="pagination justify-content-center">
      <!-- 이전페이지 -->
      {% if posts.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page={{ posts.previous_page_number }}">이전</a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
        </li>
      {% endif %}
      <!-- 페이지리스트 -->
      {% for page_number in posts.paginator.page_range %}
        {% if page_number == posts.number %}
          <li class="page-item active" aria-current="page">
            <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
          </li>
        {% endif %}
      {% endfor %}
      <!-- 다음페이지 -->
      {% if posts.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ posts.next_page_number }}">다음</a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
        </li>
      {% endif %}
    </ul>
    <!-- 페이징처리 끝 -->
  </div>
</section>
{% endblock content %}
{% block js %}{% endblock js %}

communities/templates/communities/create.html
{% extends 'base.html' %}

{% load static %}
{% load django_bootstrap5 %}

{% block title %} | 새 글 작성 
{% endblock title %}

{% block content %}
<section class="mainbg">
  <div class="container">
    <div class="boxbg p-5">
      <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form post_form %}
        <div class="form-group d-flex justify-content-center my-3">
          <button type="submit" class="btn btn-all">등록</button>
          <a href="{% url 'communities:board' %}" class="btn likebtn mx-3">취소</a>
        </div>
      </form>
    </div>
  </div>
</section>
{% endblock content %}
{% block js %}{% endblock js %}

communities/templates/communities/detail.html
{% extends 'base.html' %}

{% load static %}
{% load django_bootstrap5 %}

{% block title %}
  {{ post.title }}
{% endblock title %}

{% block content %}
  <section class="mainbg">
    <div class="container-lg">
      <!--게시글 디테일-->
      <div class="card boxbg mb-3">
        <div class="card-header">
          <h3>{{ post.title }}</h3>
          <h5 class="card-title">{{ post.name }}</h5>
        </div>
        <div class="card-body d-flex justify-content-between">
          <p class="card-subtitle text-muted">{{ post.created_at }}</p>
          <p class="card-subtitle text-muted">
            <i class="fa fa-comment" aria-hidden="true"></i>
            {{ total_comments }}</p>
        </div>
        {% if post.image %}
          <img src="{{ post.image.url }}" alt="{{ post.img_path }}" style="height: 31.25rem; width: auto; object-fit: contain;" class="card-img d-block user-select-none" width="auto" height="200" viewbox="0 0 318 180">
        {% else %}
          <img src="{% static 'images/base/logo.png' %}" alt="No_images" style="height: 31.25rem; width: auto; object-fit: contain;" class="card-img d-block user-select-none" width="auto" height="200" viewbox="0 0 318 180">
        {% endif %}
        <div class="card-body" style="min-height: 250px">
          <p class="card-text text-wrap">{{ post.content|striptags }}</p>
        </div>
      </div>
      <!--게시글 아래 버튼 묶음-->
      <div class="d-flex justify-content-between my-3">
        <a href="{% url 'communities:board' %}" type="button" class="card-link btn btn-secondary">
          <i class="fas fa-stream mx-1"></i>목록</a>
        <div>
          <a href="{% url 'communities:update' post.pk %}" type="button" class="card-link btn likecxlbtn">수정</a>
          <button type="button" class="btn likebtn mx-2" data-bs-toggle="modal" data-bs-target="#exampleModal">
            삭제
          </button>
        </div>
      </div>
      <!-- 삭제 모달-->
      <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title">정말 삭제하시겠습니까?</h5>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
                <span aria-hidden="true"></span>
              </button>
            </div>
            <div class="modal-footer">
              <form action="{% url 'communities:delete' post.pk %}" method="POST">
                {% csrf_token %}
                <input type="submit" class="btn btn-danger" value="삭제">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">
                  취소
                </button>
              </form>
            </div>
          </div>
        </div>
      </div>
      <!--댓글-->
      <div class="card my-5">
        <div class="card-header">
          <i class="fa-regular fa-comment-smile"></i>리뷰
          {{ total_comments }}개</h6>
      </div>
      <div class="card-body">
        <ul class="list-group list-group-flush">
          {% for comment in comments %}
            <li class="list-group-item mb-3">
              <p>{{ comment.title }}</p>
              <p>{{ comment.rating }}</p>
              <p>{{ comment.content }}</p>
              <div class="py-2">
                <a href="#" type="button" class="btn btn-purple btn-sm">수정</a>
                <a href="{% url 'communities:delete_comment' post.pk comment.pk %}" type="button" class="btn btn-pink btn-sm" method="post">삭제
                </a>
              </div>
            </li>
            {% empty %}
            <li class="list-group-item my-5">작성된 댓글이 없습니다.</li>
          {% endfor %}
        </ul>
      </div>
      <div class="card-footer">
        <form action="{% url 'communities:create_comment' post.pk %}" method="post" enctype="multipart/form-data">
          {% csrf_token %}
          {% bootstrap_form comment_form %}
          <button id="" type="submit" class="btn btn-all btn-sm">등록</button>
        </form>
      </div>
    </div>
  </section>
</div>
{% endblock content %}
{% block js %}{% endblock js %}

communities/templates/communities/update.html
{% extends 'base.html' %}

{% load static %}
{% load django_bootstrap5 %}

{% block title %}
  {{ post_form.title }}
{% endblock title %}

{% block content %}
<section class="mainbg">
  <div class="container-lg">
    <div class="boxbg">
      <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form post_form %}
        <div class="form-group my-3 d-flex justify-content-between">
          <a href="{% url 'communities:detail' post_pk %}" class="btn btn-purple">뒤로가기</a>
          <button type="submit" class="btn btn-all">등록</button>
        </div>
      </form>
    </div>
  </div>
</section>
{% endblock content %}
{% block js %}{% endblock js %}