accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("", views.main, name="main"),
    path("signup/", views.signup, name="signup"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("index/", views.index, name="index"),
    path("<int:pk>", views.profile, name="profile"),
    path("update/", views.update, name="update"),
    path("password/", views.change_password, name="change_password"),
    path("delete/", views.delete, name="delete"),
    path("<int:pk>/follow/", views.follow, name="follow"),
    path("login/kakao/", views.kakao_request, name="kakao"),
    path("login/kakao/callback/", views.kakao_callback),
    path("login/naver/", views.naver_request, name="naver"),
    path("login/naver/callback/", views.naver_callback),
]

adultonly/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("accounts/", include("allauth.urls")),
    path("articles/", include("articles.urls")),
    path("communities/", include("communities.urls")),
    path("ratings/", include("star_ratings.urls", namespace="ratings")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

articles/urls.py
from django.urls import path
from . import views

app_name = "articles"

urlpatterns = [
    path("", views.index, name="index"),
    path("home", views.home, name="home"),
    path("board/", views.board, name="board"),
    path("<int:pk>/", views.detail, name="detail"),
    path("likes/", views.likes, name="likes"),
    path("create/", views.create, name="create"),
    path("<int:pk>/update/", views.update, name="update"),
    path("<int:pk>/delete/", views.delete, name="delete"),
    path(
        "<int:pk>/comments/<int:comment_pk>/delete/",
        views.delete_comment,
        name="delete_comment",
    ),
    path("search/", views.search_results, name="search"),
    path("aboutus/", views.aboutus, name="aboutus"),
    path("board/<int:pk>/", views.board_filter, name="board_filter"),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from PIL import Image
from PIL import ExifTags
from io import BytesIO
from django.core.files import File


class User(AbstractUser):
    is_staff = models.BooleanField(default=False)
    is_admin = models.BooleanField(default=False)
    is_user = models.BooleanField(default=False)
    followings = models.ManyToManyField(
        "self", symmetrical=False, related_name="followers"
    )
    kakao_id = models.BigIntegerField(null=True, unique=True)
    naver_id = models.CharField(null=True, unique=True, max_length=100)
    profile_pic = models.ImageField(
        upload_to="profile/%Y%m%d/",
        default="../static/images/profile/default.png",
        null=True,
    )
    date_created = models.DateTimeField(auto_now_add=True, null=True)

    @property
    def full_name(self):
        return f"{self.last_name}{self.first_name}"

articles/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from django.conf import settings
from .utils import get_latitude_longitude


# Create your models here.
class Restaurant(models.Model):
    title = models.CharField(max_length=80)
    content = models.TextField()
    address = models.TextField()
    address_detail = models.TextField()
    image = models.ImageField(upload_to="articles/", blank=True, max_length=500)
    phone_number = models.CharField(max_length=30, null=True)
    longitude = models.FloatField()
    latitude = models.FloatField()
    cusine_code = models.IntegerField(null=True)
    subcusine_code = models.IntegerField(null=True)
    like_users = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name="like_restaurant"
    )
    # tags=models.ManyToManyField('Tag', blank=True)
    # created_at = models.DateTimeField(auto_now_add=True)
    # updated_at = models.DateTimeField(auto_now=True) 
    user = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, on_delete=models.CASCADE)
    def save(self, *args, **kwargs):
        self.latitude, self.longitude = get_latitude_longitude(self.address)
        super(Restaurant, self).save(*args, **kwargs)

class ArticleComment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE)
    title = models.CharField(max_length=80)
    rating = models.IntegerField(
        validators=[MinValueValidator(0), MaxValueValidator(5)]
    )
    content = models.TextField()
    image = models.ImageField(upload_to="review/", blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    # 유저, 추천 추가하기 이미지 여러개 모델 추가해서 fk 넣기

# class Tag(models.Model):
#     name=models.CharField(max_length=10)

#     def __str__(self) : 
#         return self.name #해시태그를 자신의 이름으로 보여준다

communities/models.py
from django.db import models
from django.conf import settings


# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=80)
    content = models.TextField()
    image = models.ImageField(upload_to="communities/", blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)


class Comment(models.Model):
    post = models.ForeignKey("Post", on_delete=models.CASCADE)
    content = models.CharField(max_length=200)
    image = models.ImageField(upload_to="communities/comment/", blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserChangeForm


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ["username", "email", "password1", "password2"]


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = (
            "last_name",
            "first_name",
            "email",
            "profile_pic",
        )
        labels = {
            "profile_pic": "프로필 사진",
        }

accounts/views.py
from multiprocessing import AuthenticationError
from datetime import datetime
from django.shortcuts import render, redirect
from .forms import CustomUserCreationForm, CustomUserChangeForm
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth import get_user_model, update_session_auth_hash
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
import requests
from django.http import JsonResponse
from django.contrib import messages


# Create your views here.
def main(request):
    return render(request, "accounts/main.html")


def signup(request):
    if request.method == "POST":
        if request.POST.get("email_id") and request.POST.get("email_address"):
            email_address = "@".join(
                [request.POST.get("email_id"), request.POST.get("email_address")]
            )
        else:
            email_address = "@".join([request.POST.get("username"), "aa.com"])
        new_request = {
            "username": request.POST.get("username"),
            "password1": request.POST.get("password1"),
            "password2": request.POST.get("password2"),
            "email": email_address,
            "csrfmiddlewaretoken": request.POST.get("csrfmiddlewaretoken"),
        }
        form = CustomUserCreationForm(new_request)
        if form.is_valid():

            user_form = form.save(commit=False)
            if request.POST.get("job") == "2":
                user_form.is_staff = True
            elif request.POST.get("job") == "1":
                user_form.is_user = True
            form.save()
            return redirect("accounts:main")
        else:
            form = CustomUserCreationForm()
            val = 1
            context = {
                "form": form,
                "val": val,
            }
            return render(request, "accounts/signup.html", context)
    else:
        check_user = request.GET.get("userId")
        if check_user:
            check_in = get_user_model().objects.filter(username=check_user)
            if check_in:
                check = True
            else:
                check = False
            context = {
                "check": check,
            }
            return JsonResponse(context)
        else:
            form = CustomUserCreationForm()
            context = {
                "form": form,
            }
            return render(request, "accounts/signup.html", context)


def login(request):
    if request.user.is_anonymous:
        if request.method == "POST":
            form = AuthenticationForm(request, data=request.POST)
            if form.is_valid():
                auth_login(request, form.get_user())
                return redirect(request.GET.get("next") or "accounts:main")
        else:
            form = AuthenticationForm()

        context = {"form": form}
        return render(request, "accounts/login.html", context)
    else:
        return redirect("accounts:index")


def logout(request):
    auth_logout(request)
    return redirect("accounts:main")


def index(request):
    users = get_user_model().objects.all()
    context = {
        "users": users,
    }
    return render(request, "accounts/index.html", context)


def profile(request, pk):
    user = get_user_model().objects.get(pk=pk)
    context = {"user": user}
    return render(request, "accounts/profile.html", context)


@login_required
def update(request):
    if request.method == "POST":
        form = CustomUserChangeForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect("accounts:profile", request.user.pk)
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {
        "form": form,
    }
    return render(request, "accounts/update.html", context)


@login_required
def change_password(request):
    if request.method == "POST":
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect("accounts:index")
    else:
        form = PasswordChangeForm(request.user)
    context = {"form": form}
    return render(request, "accounts/change_password.html", context)


@login_required
def delete(request):
    request.user.delete()
    auth_logout(request)
    return redirect("articles:index")


@login_required
def follow(request, pk):
    user = get_user_model().objects.get(pk=pk)

    if request.user == user:
        return redirect("accounts:profile", pk)
    if request.user in user.followers.all():
        user.followings.remove(request.user)
    else:
        user.followings.add(request.user)
    return redirect("accounts:profile", pk)


def naverlogin(request):
    return render(request, "accounts/naverlogin.html")


import secrets

state_token = secrets.token_urlsafe(16)


def kakao_request(request):
    kakao_api = "https://kauth.kakao.com/oauth/authorize?response_type=code"
    redirect_uri = "http://localhost:8000/accounts/login/kakao/callback"
    client_id = "72b73a1d5e11f6c8e5ebb51f86c0dfab"  # 배포시 보안적용 해야함
    return redirect(f"{kakao_api}&client_id={client_id}&redirect_uri={redirect_uri}")


def kakao_callback(request):
    data = {
        "grant_type": "authorization_code",
        "client_id": "72b73a1d5e11f6c8e5ebb51f86c0dfab",  # 배포시 보안적용 해야함
        "redirect_uri": "http://localhost:8000/accounts/login/kakao/callback",
        "code": request.GET.get("code"),
    }
    kakao_token_api = "https://kauth.kakao.com/oauth/token"
    access_token = requests.post(kakao_token_api, data=data).json()["access_token"]

    headers = {"Authorization": f"bearer ${access_token}"}
    kakao_user_api = "https://kapi.kakao.com/v2/user/me"
    kakao_user_information = requests.get(kakao_user_api, headers=headers).json()

    kakao_id = kakao_user_information["id"]
    kakao_nickname = kakao_user_information["properties"]["nickname"]
    kakao_profile_image = kakao_user_information["properties"]["profile_image"]

    if get_user_model().objects.filter(kakao_id=kakao_id).exists():
        kakao_user = get_user_model().objects.get(kakao_id=kakao_id)
    else:
        kakao_login_user = get_user_model()()
        kakao_login_user.username = kakao_nickname
        kakao_login_user.kakao_id = kakao_id
        kakao_login_user.set_password(str(state_token))
        kakao_login_user.save()
        kakao_user = get_user_model().objects.get(kakao_id=kakao_id)
    auth_login(request, kakao_user, backend="django.contrib.auth.backends.ModelBackend")
    return redirect(request.GET.get("next") or "accounts:index")


def naver_request(request):
    naver_api = "https://nid.naver.com/oauth2.0/authorize?response_type=code"
    client_id = "mwAzJRdaHS860HumilZ7"  # 배포시 보안적용 해야함
    redirect_uri = "http://localhost:8000/accounts/login/naver/callback"
    state_token = secrets.token_urlsafe(16)
    return redirect(
        f"{naver_api}&client_id={client_id}&redirect_uri={redirect_uri}&state={state_token}"
    )


def naver_callback(request):
    data = {
        "grant_type": "authorization_code",
        "client_id": "mwAzJRdaHS860HumilZ7",  # 배포시 보안적용 해야함
        "client_secret": "Aa7AEd9pZ6",
        "code": request.GET.get("code"),
        "state": request.GET.get("state"),
        "redirect_uri": "http://localhost:8000/accounts/login/naver/callback",
    }
    naver_token_request_url = "https://nid.naver.com/oauth2.0/token"
    access_token = requests.post(naver_token_request_url, data=data).json()[
        "access_token"
    ]

    headers = {"Authorization": f"bearer {access_token}"}
    naver_call_user_api = "https://openapi.naver.com/v1/nid/me"
    naver_user_information = requests.get(naver_call_user_api, headers=headers).json()

    naver_id = naver_user_information["response"]["id"]
    naver_nickname = naver_user_information["response"]["nickname"]

    if get_user_model().objects.filter(naver_id=naver_id).exists():
        naver_user = get_user_model().objects.get(naver_id=naver_id)
    else:
        naver_login_user = get_user_model()()
        naver_login_user.username = naver_nickname
        naver_login_user.naver_id = naver_id
        naver_login_user.set_password(str(state_token))
        naver_login_user.save()
        naver_user = get_user_model().objects.get(naver_id=naver_id)
    auth_login(request, naver_user, backend="django.contrib.auth.backends.ModelBackend")

    return redirect(request.GET.get("next") or "accounts:index")

accounts/templates/accounts/change_password.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load static %}
{% block content %}
<section class="mainbg">
  <div class="container mt-5 py-5 d-flex justify-content-center">
    <div class="boxbg p-5">
      <h2 class="text-center">비밀번호 변경</h2>
      <form action="{% url 'accounts:change_password' %}" method="POST">
        {% csrf_token %}
        {% bootstrap_form form%}
        <input class="btn btn-all my-2" type="button" value="변경완료">
      </form>
    </div>
  </div>
</section>
{% endblock content %}

accounts/templates/accounts/detail.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load static %}
{% block content %}
  <h1>{{ user.username }}님의 프로필</h1>

{% endblock content %}

accounts/templates/accounts/index.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load static %}
{% block content %}
<section class="mainbg px-3">
  <div class="container">
    <h1 class="text-center">회원목록</h1>
      <div class="boxbg">
      <table class="table table-hover mt-3">
        <thead>
          <tr>
            <th scope="col">번호</th>
            <th scope="col">닉네임</th>
            <th scope="col">이메일</th>
          </tr>
        </thead>
        <tbody>
          {% for user in users %}
          {% if user.is_superuser != 1 %}
          <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>
              <a href="{% url 'accounts:profile' user.pk %}">{{ user.username }}</a>
            </td>
            <td>{{ user.email }}</td>
          </tr>
          {% endif %}
          {% endfor %}
        </tbody>
      </table>
      <a class="btn btn-all my-3" href="{% url 'accounts:main' %}">메인으로</a>
      <a class="btn btn-pink my-3" href="{% url 'articles:board' %}">맛집리스트로</a>
    </div>
  </div>
</section>
{% endblock content %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}
{% block content %}

<section class="loginbg">
  <div class="container d-flex justify-content-center">
    <div class="boxbg boxbgwid p-5">
      <h1 class="text-center mb-3">로그인</h1>
      <form action="{% url 'accounts:login' %}" method='POST' onsubmit="return frm_check();">
        {% csrf_token %}
        {% render_field form.username class="form-control w-70" placeholder="아이디를 입력하세요" type="text" name="id" id="logId" %}
        {% render_field form.password class="form-control w-70 my-5" placeholder="비밀번호를 입력하세요" %}
        <input class="form-control btn likecxlbtn" type="submit" value="로그인">
        <p class="text-center my-5">회원이 아니신가요? 👉 <a href="{% url 'accounts:signup' %}">회원가입</a></p>
      </form>
        <!--아이디저장, 찾기 묶음-->
        <div class="box d-flex flex-row justify-content-between my-5">
        <span class="input-wrap">
          <input type="checkbox" name="saveId" id="saveId">
          <label for="saveId">
            <span></span></label>
          아이디 저장
        </span>
        {% comment %} <ul class="find d-flex flex-row">
          <li class="idSearch mx-3" id="idSearch" style="cursor: hand; cursor: pointer">아이디 찾기</li>
          <li class="pwSearch" id="pwSearch" style="cursor: hand; cursor: pointer">비밀번호 찾기</li>
        </ul> {% endcomment %}
      </div>
      {% load socialaccount %}
      <h5 class="text-center my-3">SNS계정으로 로그인하기</h5>
      <div class="d-flex flex-row" style="justify-content: space-evenly; ">
        <a href="{% url 'accounts:login' %}kakao"><img src="{% static 'images/login/kakaoo.png' %}" alt="kakaologin"></a>
        <a href="{% url 'accounts:login' %}naver"><img class="socialbtn" src="{% static 'images/login/nnaver.png' %}" alt="naverlogin"></a>
      </div>
     
    </div>
  </div>
</section>
{% endblock content %}
{% block js %}

  <script src="//code.jquery.com/jquery-1.11.0.min.js"></script>
  <script type="text/javascript">
    $(function () {

      fnInit();

    });

    function frm_check() {
      saveid();
    }

    function fnInit() {
      var cookieid = getCookie("saveid");
      console.log(cookieid);
      if (cookieid != "") {
        $("input:checkbox[id='saveId']").prop("checked", true);
        $('#logId').val(cookieid);
      }

    }

    function setCookie(name, value, expiredays) {
      var todayDate = new Date();
      todayDate.setTime(todayDate.getTime() + 0);
      if (todayDate > expiredays) {
        document.cookie = name + "=" + escape(value) + "; path=/; expires=" + expiredays + ";";
      } else if (todayDate < expiredays) {
        todayDate.setDate(todayDate.getDate() + expiredays);
        document.cookie = name + "=" + escape(value) + "; path=/; expires=" + todayDate.toGMTString() + ";";
      }

      console.log(document.cookie);
    }

    function getCookie(Name) {
      var search = Name + "=";
      console.log("search : " + search);

      if (document.cookie.length > 0) { // 쿠키가 설정되어 있다면
        offset = document
          .cookie
          .indexOf(search);
        console.log("offset : " + offset);
        if (offset != -1) { // 쿠키가 존재하면
          offset += search.length;
          // set index of beginning of value
          end = document
            .cookie
            .indexOf(";", offset);
          console.log("end : " + end);
          // 쿠키 값의 마지막 위치 인덱스 번호 설정
          if (end == -1) 
            end = document.cookie.length;
          console.log("end위치  : " + end);

          return unescape(document.cookie.substring(offset, end));
        }
      }
      return "";
    }

    function saveid() {
      var expdate = new Date();
      if ($("#saveId").is(":checked")) {
        expdate.setTime(expdate.getTime() + 1000 * 3600 * 24 * 30);
        setCookie("saveid", $("#logId").val(), expdate);
      } else {
        expdate.setTime(expdate.getTime() - 1000 * 3600 * 24 * 30);
        setCookie("saveid", $("#logId").val(), expdate);

      }
    }
  </script>
{% endblock js %}

accounts/templates/accounts/main.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}
{% block content %}
<section class="mainbg">
  <div class="container text-center mt-5 py-5">
    <div class="boxbg py-5">
      <h1 class="mb-2">환영합니다!</h1>
      {% if user.is_authenticated %}
        <h1>{{ user }}님</h1>
        <div class="my-3 d-flex flex-row justify-content-center">
          <a class="btn" href="{% url 'accounts:index' %}" style="background-color: #8372F2; color:#fff;">회원 목록</a>
          <a class="btn mx-4" href="{% url 'accounts:profile' user.pk %}" style="background-color: rgba(59, 63, 140, 1); color:#fff;">프로필</a>
          <a class="btn likebtn" href="{%  url 'accounts:logout' %}">로그아웃</a>
        </div>
      {% else %}
        <div>
          <p class="my-3">회원이면</p>
          <a class="btn likecxlbtn" href="{%  url 'accounts:login' %}">로그인</a>
        </div>
        <div>
          <p class="mt-5">비회원이면</p>
          <div class="form d-flex justify-content-center my-3">
            <a class="btn likebtn me-4" href="{%  url 'accounts:signup' %}">회원가입</a>
            <a class="btn btn-purple" href="{%  url 'articles:board' %}">비회원으로 계속</a>
          </div>
        </div>
      {% endif %}
    </div>
  </div>
</section>
{% endblock content %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load static %}
{% block content %}
<section class="mainbg">
  <div class="container text-center mt-5 py-5">
    <div class="boxbg py-5">
      <div class="profilepic">
      {% if user.profile_pic %}
        <img src="{{ user.profile_pic.url }}" alt="프사" class="pf_img">
        {% else %}
        <img src="{% static 'images/profile/default.png' %}" alt="프사" class="pf_img">
        {% endif %}
      </div>
      <h1 class="my-2 ">{{ user.username }}님의 프로필</h1>
      <p class="my-2">{{ user.email }}</p>
      <p class="my-2">{{ user.full_name }}</p>
      <p class="my-2">팔로우 : {{ user.followings.count }} | 팔로워 : {{ user.followers.count }}</p>
      {% if request.user != user %}
        <a href="{% url 'accounts:follow' user.pk %}">
          {% if request.user in user.followers.all %}
            <input class="btn btn-pink my-2" type="submit" value='팔로우 취소'>
          {% else %} 
            <input class="btn btn-all my-2" type="submit" value='팔로우'>
          {% endif %}
        </a>
      {% endif %}
        <h4 class="fw-bold my-3">좋아요 누른 글</h4>
        <p class="text-muted my-3">{{ user.like_articles.count }}개를 좋아합니다.</p>
        {% for article in user.like_articles.all %}
          <p>
            <a class="text-decoration-none" href="{% url 'articles:detail' article.pk %}">{{ article.title }}</a>
          </p>
        {% endfor %}
      <h3 class="my-2">작성 글</h3>
      <p class="text-muted my-3">{{ user.article_set.count }}개 작성 완료</p>
      {% for article in user.article_set.all %}
      <p>{{ forloop.counter }}
      <a href="{% url 'articles:detail' article.pk %}">{{ article.title }}</a>
      </p>
    {% endfor %}
        <h3 class="my-2">작성 댓글</h3>
        <p class="text-muted my-3">{{ user.comment_set.count }}개 작성 완료</p>
        {% for comment in user.articlecomment_set.all%}
        <p>{{ forloop.counter }}
        <a href="{% url 'articles:detail' comment.restaurant_id %}">{{ comment.content }}</a>
        </p>
        {% endfor %}

      <p class="my-3">
        {% if user.is_authenticated %}
        <a class="btn likecxlbtn" href="{% url 'accounts:index' %}">목록으로</a>
        {% if request.user == user %}
        <a class="btn likecxlbtn" href="{% url 'accounts:logout' %}">로그아웃</a>
          <a class="btn btn-purple" href="{% url 'accounts:update' %}">프로필 수정</a>
          <a class="btn likebtn" href="{% url 'accounts:delete' %}">회원탈퇴</a>  
          {% endif %}
        {% else %}
        {% endif %}
      </p>
    </div>
  </div>
</section>
{% endblock content %}
 

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load static %}
{% block content %}
<section class="mainbg">
  {% if val %}
  <script>
  alert('유효성 검사 실패!')
  </script>
{% endif %}
  <div class="back_container container mb-5">
    <div class="signup boxbg">
    <h1 class="mt-5">회원가입</h1>
    <h3 class="mb-5">가입을 통해 더 다양한 서비스를 만나보세요!</h3>
    <form action="" method='POST' id="form_check" class="w-75">
      {% csrf_token %}
      {% comment %} {% bootstrap_form form %} {% endcomment %}
      <div required class="input_form" id="info__id">
        <input id="check_id" type="text" name="username" placeholder="아이디 입력 (4~20자)"/>
        <button id="id-check">중복 확인</button>
        <p id="id-error"></p>
      </div>
      <div required class="password_form" id="info__pw">
      <input class="mt-5" type="password" autoComplete="off" id="password1" name="password1" placeholder="비밀번호 입력(문자,숫자,특수문자 포함 8~20자)"/>
      <p id="pass_1"></p>
      <input class="my-5" type="password" autoComplete="off" id="password2" name="password2" placeholder="비밀번호 재입력"/>
      <p id="pass_2"></p>
      <div class="error-msg"></div>
    </div>
    <div required class="email_form">
      <input type="text" name="email_id" placeholder="이메일 주소"/>
      <p>@</p>
      <input class="text" name="email_address" id="domain-txt" type="text"/>
      <select class="box" id="domain-list">
        <option value="type">직접 입력</option>
        <option value="naver.com">naver.com</option>
        <option value="google.com">google.com</option>
        <option value="hanmail.net">hanmail.net</option>
        <option value="nate.com">nate.com</option>
        <option value="kakao.com">kakao.com</option>
      </select>
    </div>
    {% comment %} <div required class="year_form">
      <input class="mt-5" type="text" placeholder="년도"/>
      <input class="mt-5" type="text" placeholder="월"/>
      <input class="mt-5" type="text" placeholder="일"/>
    </div> {% endcomment %}
    <div required class="job_form">
    <input name="job" type="checkbox" value="1" autofocus onclick="doOpenCheck(this);" id="normal">
    <label name="job_pos" id="normal" style="color: gray;" for="normal"><div class="job_btn">일반인</div></label>
    <input name="job" type="checkbox" value="2" onclick="doOpenCheck(this);" id="owner">
    <label name="job_pos" id="owner" style="color: gray;" for="owner"><div class="job_btn">사장님</div></label>
    </div>
    <div class="submitBtn">
      <div id="result-check"></div>
      <input type="button" id="submitbtn" value="가입하기">
    </div>
    <p class="text-center my-5">이미 회원이신가요? 👉 <a href="{% url 'accounts:login' %}">로그인</a></p>
    </form>
  </div>
  </div>
</section>
{% endblock content %}

accounts/templates/accounts/update.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load static %}
{% block content %}
<section class="mainbg">
  <div class="container mt-5 py-5">
    <div class="boxbg py-5 px-5">
      <h1 class="text-center">프로필 업데이트</h1>
      <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input class="btn btn-all my-2" type="submit" value="저장">
        <a class="btn btn-pink my-2" href="{% url 'accounts:change_password' %}">비밀번호 변경</a>
     </form>
    </div>
  </div>
</section>
{% endblock content %}