accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("", views.main, name="main"),
    path("signup/", views.signup, name="signup"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("index/", views.index, name="index"),
    path("<int:pk>", views.profile, name="profile"),
    path("update/", views.update, name="update"),
    path("password/", views.change_password, name="change_password"),
    path("delete/", views.delete, name="delete"),
    path("<int:pk>/follow/", views.follow, name="follow"),
    path("login/kakao/", views.kakao_request, name="kakao"),
    path("login/kakao/callback/", views.kakao_callback),
    path("login/naver/", views.naver_request, name="naver"),
    path("login/naver/callback/", views.naver_callback),
]

adultonly/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("accounts/", include("allauth.urls")),
    path("articles/", include("articles.urls")),
    path("communities/", include("communities.urls")),
    path("ratings/", include("star_ratings.urls", namespace="ratings")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

articles/urls.py
from django.urls import path
from . import views

app_name = "articles"

urlpatterns = [
    path("", views.index, name="index"),
    path("home", views.home, name="home"),
    path("board/", views.board, name="board"),
    path("<int:pk>/", views.detail, name="detail"),
    path("likes/", views.likes, name="likes"),
    path("create/", views.create, name="create"),
    path("<int:pk>/update/", views.update, name="update"),
    path("<int:pk>/delete/", views.delete, name="delete"),
    path(
        "<int:pk>/comments/<int:comment_pk>/delete/",
        views.delete_comment,
        name="delete_comment",
    ),
    path("search/", views.search_results, name="search"),
    path("aboutus/", views.aboutus, name="aboutus"),
    path("board/<int:pk>/", views.board_filter, name="board_filter"),
]

articles/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from django.conf import settings
from .utils import get_latitude_longitude


# Create your models here.
class Restaurant(models.Model):
    title = models.CharField(max_length=80)
    content = models.TextField()
    address = models.TextField()
    address_detail = models.TextField()
    image = models.ImageField(upload_to="articles/", blank=True, max_length=500)
    phone_number = models.CharField(max_length=30, null=True)
    longitude = models.FloatField()
    latitude = models.FloatField()
    cusine_code = models.IntegerField(null=True)
    subcusine_code = models.IntegerField(null=True)
    like_users = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name="like_restaurant"
    )
    # tags=models.ManyToManyField('Tag', blank=True)
    # created_at = models.DateTimeField(auto_now_add=True)
    # updated_at = models.DateTimeField(auto_now=True) 
    user = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, on_delete=models.CASCADE)
    def save(self, *args, **kwargs):
        self.latitude, self.longitude = get_latitude_longitude(self.address)
        super(Restaurant, self).save(*args, **kwargs)

class ArticleComment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE)
    title = models.CharField(max_length=80)
    rating = models.IntegerField(
        validators=[MinValueValidator(0), MaxValueValidator(5)]
    )
    content = models.TextField()
    image = models.ImageField(upload_to="review/", blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    # 유저, 추천 추가하기 이미지 여러개 모델 추가해서 fk 넣기

# class Tag(models.Model):
#     name=models.CharField(max_length=10)

#     def __str__(self) : 
#         return self.name #해시태그를 자신의 이름으로 보여준다

articles/forms.py
from .models import Restaurant, ArticleComment as Comment
from django import forms


class RestaurantForm(forms.ModelForm):
    class Meta:
        model = Restaurant
        fields = [
            "title",
            "content",
            "image",
            "address",
            "address_detail",
            "phone_number",
        ]
        labels = {
            "title": "가게명",
            "content": "가게 정보",
            "image": "사진",
            "address": "주소",
            "address_detail": "상세 주소",
            "phone_number": "전화번호",
        }
        widgets = {
            "address": forms.TextInput(
                attrs={
                    "class": "form-control",
                    "id": "address_kakao",
                    "placeholder": "주소",
                }
            ),
            "address_detail": forms.TextInput(
                attrs={
                    "class": "form-control",
                    "name": "address_detail",
                    "placeholder": "상세 주소",
                }
            ),
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = [
            "title",
            "rating",
            "content",
            "image",
        ]
        labels = {
            "title": "제목",
            "rating": "평가",
            "content": "후기",
            "image": "사진",
        }

# class TagForm(forms.ModelForm):
#     class Meta:
#         model= Tag
#         fields=['name']

articles/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_safe
from .models import Restaurant, ArticleComment as Comment
from .forms import RestaurantForm, CommentForm
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from .utils import get_latitude_longitude
from django.http import JsonResponse
import os
import dotenv
from django.contrib import messages
from django.contrib.auth.decorators import login_required


dotenv_file = dotenv.find_dotenv()
dotenv.load_dotenv(dotenv_file)
# from django.contrib.auth.decorators import login_required

# Create your views here.
@require_safe
def index(request):
    return render(request, "articles/index.html")


def home(request):
    restaurants_1 = Restaurant.objects.order_by("-like_users")[:3]
    restaurants_2 = Restaurant.objects.order_by("-like_users")[3:6]
    restaurants_3 = Restaurant.objects.order_by("-like_users")[6:9]
    restaurants_4 = Restaurant.objects.order_by("-like_users")[9:12]
    context = {
        "restaurants_1": restaurants_1,
        "restaurants_2": restaurants_2,
        "restaurants_3": restaurants_3,
        "restaurants_4": restaurants_4,
    }
    return render(request, "articles/home.html", context)


def board_filter(request, pk):
    restaurants = Restaurant.objects.filter(cusine_code=pk).order_by("-pk")
    page = request.GET.get("page")
    paginator = Paginator(restaurants, 6)
    try:
        page_obj = paginator.get_page(page)
    except PageNotAnInteger:
        page = 1
        page_obj = paginator.page(page)
    except EmptyPage:
        page = paginator.num_pages
        page_obj = paginator.page(page)
    print(page_obj)
    context = {
        "restaurants": page_obj,
    }
    return render(request, "articles/board.html", context)


def board(request):
    restaurants = Restaurant.objects.order_by("-pk")
    page = request.GET.get("page")
    paginator = Paginator(restaurants, 6)
    try:
        page_obj = paginator.get_page(page)
    except PageNotAnInteger:
        page = 1
        page_obj = paginator.page(page)
    except EmptyPage:
        page = paginator.num_pages
        page_obj = paginator.page(page)

    avg_list = []
    for page in page_obj:
        reviews = page.articlecomment_set.values()
        try:
            setattr(
                page, "avg_rating", sum([x["rating"] for x in reviews]) // len(reviews)
            )
        except:
            setattr(page, "avg_rating", 0)

    context = {
        "restaurants": page_obj,
    }
    return render(request, "articles/board.html", context)


@login_required
def detail(request, pk):
    restaurant = get_object_or_404(Restaurant, pk=pk)
    lat, lon = get_latitude_longitude(restaurant.address)
    form = CommentForm(request.POST, request.FILES or None)
    client_id = os.environ["naver_id"]
    data = {}
    if request.method == "POST":
        if form.is_valid():
            comment = form.save(commit=False)
            comment.restaurant = restaurant
            comment.user = request.user
            comment.save()
        return redirect("articles:detail", restaurant.pk)

    reviews = restaurant.articlecomment_set.values()
    avg_rating = 0
    if reviews:
        avg_rating = sum([x["rating"] for x in reviews]) // len(reviews)

    context = {
        "restaurant": restaurant,
        "comments": restaurant.articlecomment_set.all().order_by("-created_at"),
        "comment_form": form,
        "latitude": lat,
        "longitude": lon,
        "client_id": client_id,
        "avg_rating": avg_rating,
    }

    return render(request, "articles/detail.html", context)


@login_required
def create(request):
    if request.method == "POST":
        restaurant_form = RestaurantForm(request.POST, request.FILES)
        if restaurant_form.is_valid():
            restaurant = restaurant_form.save(commit=False)
            restaurant.user = request.user
            restaurant.save()
            messages.success(request, "맛집으로 등록되었습니다.")
            return redirect("articles:board")
    else:
        restaurant_form = RestaurantForm()
    context = {
        "restaurant_form": restaurant_form,
    }
    return render(request, "articles/create.html", context)


# @login_required
def update(request, pk):
    restaurant = get_object_or_404(Restaurant, pk=pk)
    if request.user == restaurant.user:
        if request.method == "POST":
            restaurant_form = RestaurantForm(
                request.POST, request.FILES, instance=restaurant
            )
            if restaurant_form.is_valid():
                restaurant_form.save()
                messages.success(request, "맛집 정보가 수정되었습니다.")
                return redirect("articles:detail", pk)
        else:
            restaurant_form = RestaurantForm(instance=restaurant)
    context = {
        "restaurant_form": restaurant_form,
        "restaurant_pk": restaurant.pk,
    }
    return render(request, "articles/update.html", context)


def delete(request, pk):
    restaurant = Restaurant.objects.get(pk=pk)
    if request.method == "POST":
        restaurant.delete()
        return redirect("articles:board")
    context = {
        "restaurant": restaurant,
    }
    return redirect("articles:detail", context)


def delete_comment(request, pk, comment_pk):
    comment = Comment.objects.get(pk=comment_pk)
    comment.delete()
    return redirect("articles:detail", pk)


def likes(request):
    if request.user.is_authenticated:
        restaurant = get_object_or_404(Restaurant, pk=request.POST.get("pk"))

        if restaurant.like_users.filter(pk=request.user.pk).exists():
            restaurant.like_users.remove(request.user)
            is_liked = False

        else:
            restaurant.like_users.add(request.user)
            is_liked = True
        context = {
            "is_liked": is_liked,
            "likeCount": restaurant.like_users.count(),
        }
        return JsonResponse(context)


def search_results(request):
    if request.is_ajax():
        res = None
        restaurant = request.POST.get("restaurant")
        kw = Restaurant.objects.filter(title__icontains=restaurant)
        if len(kw) > 0 and len(restaurant) > 0:
            data = []
            for k in kw:
                item = {
                    "pk": k.pk,
                    "title": k.title,
                    "address": k.address + " " + k.address_detail,
                    "phone_number": k.phone_number,
                    "image": str(k.image),
                }
                data.append(item)
            res = data
        else:
            res = "검색결과가 없습니다."
        return JsonResponse(
            {
                "restaurant": res,
            }
        )
    return JsonResponse({})


def aboutus(request):
    return render(request, "articles/aboutus.html")


@login_required
def create_comment(request, pk):
    restaurant = Restaurant.objects.get(pk=pk)
    comment_form = CommentForm(request.POST)
    if comment_form.is_valid():
        comment = comment_form.save(commit=False)
        comment.restaurant = restaurant
        comment.user = request.user
        comment.save()
    return redirect("articles:detail", restaurant.pk)

articles/templates/articles/aboutus.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}
{% block title %} | about us{% endblock title %}
{% block content %}
<section class="aboutusbg">
  <div class="card aboutus">
    <div class="card-body d-flex flex-column justify-content-around align-content-center align-items-center py-5">
      <small class="my-5">2022. 10. 31 - 2022. 11. 7</small>
      <i class="mt-5">created by</i>
      <P style="line-height: 200%;">노은빈<br>김다솔<br>최근영<br>황성욱</P>
      <h5 class="my-5">[멀티잇] 풀스택 개발자 취업캠프</h5>
    </div>
  </div>
</section>
{% endblock content %}
{% block js %}
{% endblock js %}

articles/templates/articles/board.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}
{% block title %} | 맛집{% endblock title %}
{% block content %}
<section class="mainbg">
  <div class="container">
    <h1 id="mat">
      맛집 리스트
    </h1>
    <!--해쉬태그-->
      <div class="select_tag">
        <button class="tag_list" id="all">
          <img src="{% static 'images/board/all.png' %}" style="weight:40px; height:40px;" alt="">
          {% comment %} <a href="https://www.flaticon.com/free-icons/korea" title="korea icons">Korea icons created by Freepik - Flaticon</a> {% endcomment %}
          <p style="font-size: 12px; margin-top: 5px; font-weight: bold;">All</p>
        </button>
        <button class="tag_list" value="1" id="kor">
          <img src="{% static 'images/board/korea.png' %}" style="weight:40px; height:40px;" alt="">
          {% comment %} <a href="https://www.flaticon.com/free-icons/korea" title="korea icons">Korea icons created by Freepik - Flaticon</a> {% endcomment %}
          <p style="font-size: 12px; margin-top: 5px; font-weight: bold;">한식</p>
        </button>
        <button class="tag_list" value="2" id="cha">
          <img src="{% static 'images/board/china.png' %}" style="weight:40px; height:40px;" alt="">
          {% comment %} <a href="https://www.flaticon.com/free-icons/china" title="china icons">China icons created by Freepik - Flaticon</a> {% endcomment %}
          <p style="font-size: 12px; margin-top: 5px; font-weight: bold;">중식</p>
        </button>
        <button class="tag_list" value="3" id="jap">
          <img src="{% static 'images/board/japan.png' %}" style="weight:40px; height:40px;" alt="">
          {% comment %} <a href="https://www.flaticon.com/free-icons/japan" title="japan icons">Japan icons created by Freepik - Flaticon</a> {% endcomment %}
          <p style="font-size: 12px; margin-top: 5px; font-weight: bold;">일식</p>
        </button>
        <button class="tag_list" value="4" id="yang">
          <img src="{% static 'images/board/italy.png' %}" style="weight:40px; height:40px;" alt="">
          {% comment %} <a href="https://www.flaticon.com/free-icons/italy" title="italy icons">Italy icons created by Freepik - Flaticon</a> {% endcomment %}
          <p style="font-size: 12px; margin-top: 5px; font-weight: bold;">양식</p>
        </button>
        <button class="tag_list" value="5" id="world">
          <img src="{% static 'images/board/world.png' %}" style="weight:40px; height:40px;" alt="">
          {% comment %} <a href="https://www.flaticon.com/free-icons/world" title="world icons">World icons created by srip - Flaticon</a> {% endcomment %}
          <p style="font-size: 12px; margin-top: 5px; font-weight: bold;">세계 음식</p>
        </button>
        <button class="tag_list" value="7" id="caf">
          <img src="{% static 'images/board/coffee.png' %}" style="weight:40px; height:40px;" alt="">
          {% comment %} <a href="https://www.flaticon.com/free-icons/cafe" title="cafe icons">Cafe icons created by Freepik - Flaticon</a> {% endcomment %}
          <p style="font-size: 12px; margin-top: 5px; font-weight: bold;">카페</p>
        </button>
        <button class="tag_list" value="8" id="pub">
          <img src="{% static 'images/board/toast.png' %}" style="weight:40px; height:40px;" alt="">
          {% comment %} <a href="https://www.flaticon.com/free-icons/beer" title="beer icons">Beer icons created by Freepik - Flaticon</a> {% endcomment %}
          <p style="font-size: 12px; margin-top: 5px; font-weight: bold;">펍</p>
        </button>
      </div>
    </div>
  <div class="container-lg" id="board_out">
    {% if user.is_authenticated and user.is_staff == 1 %}
      <a href="{% url 'articles:create' %}" type="button" class="btn btn-all mb-4">맛집 등록</a>
    {% endif %}
    <!-- 카드 리스트 -->
    <div class="row row-cols-1 row-cols-md-3 g-4 mb-5" id="masterdiv">
      {% for restaurant in restaurants %}
        <div class="col">
          <div class="page_card mt-3 px-2 py-3">
            <a href="{% url 'articles:detail' restaurant.pk %}" class="card-link text-decoration-none">
              <h5 class="card-header mb-2">{{ restaurant.title }}</h5>
            </a>
            <div class="card-body d-flex flex-column justify-content-between" style="color:rgba(41, 39, 89, 1);">
              <h6 class="card-title text-muted"><i class="fa-solid fa-location-dot"></i>  {{ restaurant.address }}</h6>
              {% if restaurant.phone_number%}
              <small class="card-text mb-2"><i class="fa-solid fa-phone"></i> {{ restaurant.phone_number }}</small>
              {% else %}
              <small><i class="fa-solid fa-phone"></i></small>
              {% endif %}
            </div>
            {% if restaurant.pk > 889  %}
            <img src= "{{ restaurant.image.url }}" alt="{{ restaurant.image  }}" class="card-img d-block user-select-none my-2" width="100%" height="200" viewbox="0 0 318 180">
            {% else %}
            <img src= "{{ restaurant.image }}" alt="{{ restaurant.image  }}" class="card-img d-block user-select-none my-2" width="100%" height="200" viewbox="0 0 318 180">
            {% endif %}
            <div class="card-body">
              <p class="card-text" name="comment-rating">{{ restaurant.avg_rating}}</p>
              <div class="card-text mt-2">좋아요 {{ restaurant.like_users.count}}</div>
              <div class="card-text mt-2">댓글 {{ restaurant.articlecomment_set.all|length}}</div>
            </div>
          </div>

        </div>
        {% endfor %}
      </div>
      <!-- 페이징처리 시작 -->
      <ul class="pagination justify-content-center py-4">
        <!-- 이전페이지 -->
        {% if restaurants.has_previous %}
          <li class="page-item d-flex flex-row">
            <a class="page-link" href="?page=1/"><i class="fa-solid fa-backward-step"></i></a>
            <a class="page-link" href="?page={{ restaurants.previous_page_number }}"><i class="fa-solid fa-chevron-left"></i></a>
          </li>
        {% else %}
          <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#"><i class="fa-solid fa-chevron-left"></i></a>
          </li>
        {% endif %}
        <!-- 페이지리스트 -->
        {% for page_number in restaurants.paginator.page_range %}
          {% if page_number >= restaurants.number|add:-2 and page_number <= restaurants.number|add:2 %}
            {% if page_number == restaurants.number %}  
              <li class="page-item active" aria-current="page">
                <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
              </li>
            {% else %}
              <li class="page-item">
                <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
              </li>
            {% endif %}
          {% endif %}
        {% endfor %}
        <!-- 다음페이지 -->
        {% if restaurants.has_next %}
          <li class="page-item d-flex flex-row">
            <a class="page-link" href="?page={{ restaurants.next_page_number }}"><i class="fa-solid fa-chevron-right"></i></a>
            <a class="page-link" href="?page={{ restaurants.paginator.num_pages }}"><i class="fa-solid fa-forward-step"></i></a>
          </li>
        {% else %}
          <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#"><i class="fa-solid fa-chevron-right"></i></a>
          </li>
        {% endif %}
      </ul>
      <!-- 페이징처리 끝 -->
    </section>
  </div>
</section>  
{% endblock content %}

{% block js %}
<script>
  var likeBtn = document.getElementById("like")
</script>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
  starRatings = document.getElementsByName('comment-rating')
  
  starRatings.forEach(starRating => {
    var rate = starRating.innerHTML
    console.log(starRatings)
  if(rate == 1){
    starRating.innerHTML = 
    `
    <span class="fa fa-star fa-3x-lg checked"></span>
    <span class="fa fa-star fa-3x-lg"></span>
    <span class="fa fa-star fa-3x-lg"></span>
    <span class="fa fa-star fa-3x-lg"></span>
    <span class="fa fa-star fa-3x-lg"></span>
    `
  }else if(rate == 2){
    starRating.innerHTML = 
    `
    <span class="fa fa-star fa-3x-lg checked"></span>
    <span class="fa fa-star fa-3x-lg checked"></span>
    <span class="fa fa-star fa-3x-lg"></span>
    <span class="fa fa-star fa-3x-lg"></span>
    <span class="fa fa-star fa-3x-lg"></span>
    `
  }else if(rate == 3){
    starRating.innerHTML = 
    `
    <span class="fa fa-star fa-3x-lg checked"></span>
    <span class="fa fa-star fa-3x-lg checked"></span>
    <span class="fa fa-star fa-3x-lg checked"></span>
    <span class="fa fa-star fa-3x-lg"></span>
    <span class="fa fa-star fa-3x-lg"></span>
    `
  }else if(rate == 4){
    starRating.innerHTML = 
    `
    <span class="fa fa-star fa-3x-lg checked"></span>
    <span class="fa fa-star fa-3x-lg checked"></span>
    <span class="fa fa-star fa-3x-lg checked"></span>
    <span class="fa fa-star fa-3x-lg checked"></span>
    <span class="fa fa-star fa-3x-lg"></span>
    `
  }else if(rate == 5){
    starRating.innerHTML = 
    `
    <span class="fa fa-star fa-3x-lg checked"></span>
    <span class="fa fa-star fa-3x-lg checked"></span>
    <span class="fa fa-star fa-3x-lg checked"></span>
    <span class="fa fa-star fa-3x-lg checked"></span>
    <span class="fa fa-star fa-3x-lg checked"></span>
    `
  }else if(rate == '0'){
    starRating.innerHTML = 
    `
    <span class="fa fa-star fa-3x-lg"></span>
    <span class="fa fa-star fa-3x-lg"></span>
    <span class="fa fa-star fa-3x-lg"></span>
    <span class="fa fa-star fa-3x-lg"></span>
    <span class="fa fa-star fa-3x-lg"></span>
    `
  }
  })
</script>
{% endblock js %}

articles/templates/articles/create.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}
{% block title %}
  | 맛집 등록{% endblock title %}
{% block content %}
  <script src="//t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js"></script>
  <section class="mainbg">
    <section class="container-lg">
      <h1 class="my-5 text-center">
        맛집 등록
      </h1>
      <div class="boxbg p-5">
        <form action="" method="POST" enctype="multipart/form-data">
          {% csrf_token %}
          {% bootstrap_form restaurant_form %}
          <div class="form-group my-3">
            <button type="submit" class="btn likecxlbtn">등록</button>
            <a href="{% url 'articles:board' %}" class="btn likebtn mx-3">취소</a>
          </div>
        </form>
      </div>
    </section>
  </section>
{% endblock content %}
{% block js %}
  <script>
    window.onload = function () {
      document
        .getElementById("address_kakao")
        .addEventListener("click", function () {
          new daum
            .Postcode({
              oncomplete: function (data) {
                document
                  .getElementById("address_kakao")
                  .value = data.address;
                document
                  .querySelector("input[name=address_detail]")
                  .focus();
              }
            })
            .open();
        });
    }
  </script>
{% endblock js %}

articles/templates/articles/index.html
{% load static %}
{% load django_bootstrap5 %}
<!doctype html>
<html lang="en">

  <head>
    <title>🔞청소년입장불가</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS v5.2.1 -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'CSS/indexstyle.css' %}">
  </head>

  <body id="body">
    <div class="d-flex flex-column h-100 my-5" style="align-items:center;">
      <div class="card_makes">
        <div class="main_img">
          <img src="{% static 'img/main_img.gif' %}" alt="로고" class="d-flex justify-content-center">
        </div>
        <div class="main_mark">
          <img src="{% static 'img/19mark.png' %}" alt="19금">
          <div class="main_content">
            <h5>만 19세 이상만 방문/이용이 가능합니다.</h5>
            <a href="{% url 'articles:home' %}" class="btn btn-danger">입장하기</a>
          </div>
        </div>
      </div>
    </div>
    <script src="{% static 'JS/index.js' %}"></script>
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.min.js" integrity="sha384-7VPbUDkoPSGFnVtYi0QogXtr74QeVeeIs99Qfg5YCF+TidwNdjvaKZX19NZ/e6oz" crossorigin="anonymous"></script>
  </body>

</html>

articles/templates/articles/update.html
{% extends 'base.html' %}

{% load static %}
{% load django_bootstrap5 %}

{% block title %} | 맛집 정보 수정
{% endblock title %}

{% block content %}
<section class="mainbg">
  <div class="container-lg">
    <h1 class="my-5 text-center">
      맛집 정보 수정
    </h1>
    <div class="boxbg">
      <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form restaurant_form %}
        <div class="form-group my-3 d-flex justify-content-between">
          <a href="{% url 'articles:detail' restaurant_pk %}" class="btn btn-primary">뒤로가기</a>
          <button type="submit" class="btn btn-primary">등록</button>
        </div>
      </form>
    </div>
  </div>
</section>
{% endblock content %}