accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("", views.main, name="main"),
    path("signup/", views.signup, name="signup"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("index/", views.index, name="index"),
    path("<int:pk>", views.profile, name="profile"),
    path("update/", views.update, name="update"),
    path("password/", views.change_password, name="change_password"),
    path("delete/", views.delete, name="delete"),
    path("<int:pk>/follow/", views.follow, name="follow"),
    path("login/kakao/", views.kakao_request, name="kakao"),
    path("login/kakao/callback/", views.kakao_callback),
    path("login/naver/", views.naver_request, name="naver"),
    path("login/naver/callback/", views.naver_callback),
]

adultonly/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("accounts/", include("allauth.urls")),
    path("articles/", include("articles.urls")),
    path("communities/", include("communities.urls")),
    path("ratings/", include("star_ratings.urls", namespace="ratings")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

articles/urls.py
from django.urls import path
from . import views

app_name = "articles"

urlpatterns = [
    path("", views.index, name="index"),
    path("home", views.home, name="home"),
    path("board/", views.board, name="board"),
    path("<int:pk>/", views.detail, name="detail"),
    path("likes/", views.likes, name="likes"),
    path("create/", views.create, name="create"),
    path("<int:pk>/update/", views.update, name="update"),
    path("<int:pk>/delete/", views.delete, name="delete"),
    path(
        "<int:pk>/comments/<int:comment_pk>/delete/",
        views.delete_comment,
        name="delete_comment",
    ),
    path("search/", views.search_results, name="search"),
    path("aboutus/", views.aboutus, name="aboutus"),
    path("board/<int:pk>/", views.board_filter, name="board_filter"),
]

communities/urls.py
from django.urls import path
from . import views

app_name = "communities"

urlpatterns = [
    path("board/", views.board, name="board"),
    path("<int:pk>/", views.detail, name="detail"),
    path("create/", views.create, name="create"),
    path("<int:pk>/update/", views.update, name="update"),
    path("<int:pk>/delete/", views.delete, name="delete"),
    path("comments/<int:pk>/", views.create_comment, name="create_comment"),
    path(
        "<int:pk>/comments/<int:comment_pk>/delete/",
        views.delete_comment,
        name="delete_comment",
    ),
]

templates/base.html
{% load static %}
{% load django_bootstrap5 %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'img/wineglass.ico' %}">
    <title>
      청소년입장불가{% block title %}{% endblock title %}
    </title>
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    {% comment %} <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script> {% endcomment %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'star-ratings/css/star-ratings.css' %}">
    <script type="text/javascript" src="{% static 'star-ratings/js/dist/star-ratings.min.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'CSS/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'CSS/signup.css' %}">
    <script src="https://kit.fontawesome.com/4402be0952.js" crossorigin="anonymous"></script>
  </head>
  <body>
    <header class="sticky-top">
      <!-- place navbar here -->
      <nav class="navbar navbar-expand-lg glassnav">
        <a class="navbar-brand" href="{% url 'articles:home' %}"><img src="{% static 'images/base/logo.png' %}" alt="임시로고" style="height:50px; margin-left: 1rem;"></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <!-- 검색 -->
        <div class="collapse navbar-collapse d-flex flex-column" id="navbarSupportedContent">
          <form class="d-flex w-50 mb-3" id="search-form" autocomplete="off">
            {% csrf_token %}
            <input type="search" id="search-input" class="form-control form-control-dark text-bg-light" placeholder="Search..." aria-label="Search">
          </form>
          <div class="p-3 bg-body rounded shadow-sm d-none w-50" id="results-box"></div> 
          <!-- 검색바 아래 게시판 -->
          <ul class="d-flex justify-content-around w-50">
            <li>
              <a href="{% url 'articles:board' %}">맛집리스트</a>
            </li>
            <li>
              <a href="{% url 'communities:board' %}">자유게시판</a>
            </li>
            <li><a href="{% url 'articles:aboutus' %}">about us</a></li>
          </ul>
        </div>

        {% if request.user.is_authenticated %}
        <div class="nav-item">
          {% if request.user.profile_pic %}
          <a href="{% url 'accounts:profile' request.user.pk %}" class="nav-link title_profile">
              <img src="{{ request.user.profile_pic.url }}" class="img_profile" alt="프로필사진">
          </a>
          {% else %}
          <a href="{% url 'accounts:profile' request.user.pk %}" class="nav-link title_profile">
          <img src="{% static 'images/profile/default.png' %}" alt="프사" class="pf_img">
        </a>
          {% endif %}
        </div>
        <div class="nav-item dropdown" style="margin: 0 100px 0 0;">
          <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fa-solid fa-circle-caret-down"></i>{{ request.user }} 님
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{% url 'accounts:profile' request.user.pk %}">My Page</a>
            <a class="dropdown-item" href="{% url 'accounts:update'  %}">정보 수정</a>
            <a class="dropdown-item" href="{% url 'accounts:index'  %}">회원 목록</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item text-warning" href="{% url 'accounts:logout' %}">로그아웃</a>

          </div>
        </div>
        {% else %}
        <div class="nav-item d-flex flex-row mx-3">
          <a class="nav-link" href="{% url 'accounts:login' %}">
            <u>Log In</u>
          </a>
          <p class="nav-item mx-3 disabled">/</p>
          <a class="nav-link" href="{% url 'accounts:signup' %}">
            <u>Sign Up</u>
          </a>
        </div>
        {% endif %}
      </nav>  
    </header> 
    <main>
      {% block content %}{% endblock content %}
    </main>
    <footer class="py-3 text-center" style="background: #F2F2F2; margin: 0;">
      <div class="my-4">
        <a href='www.google.com' target='_blank'>Google</a> |
        <a href='https://github.com/rhoeunbin/adultonly' target='_blank'>Github</a>
      </div>
      <p class="my-1">은빈.다솔.근영.성욱</p><br/>
      <p class="my-2">Copyright 2022. All Rights Reserved.</p>
    </footer>
<!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    <script src="{% static 'JS/signup.js' %}"></script>
    <script src="{% static 'JS/board.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
    {% block js %}{% endblock js %}
  </body>
</html>